/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SGN_4.h"
#include "SGN_4_aliases.h"
#include "button_inc_isr.h"
#include "Button_inc.h"
#include "Button_inc_aliases.h"
#include "Control_Reg.h"
#include "SGN_1.h"
#include "SGN_1_aliases.h"
#include "SGN_2.h"
#include "SGN_2_aliases.h"
#include "SGN_3.h"
#include "SGN_3_aliases.h"
#include "Button_dec.h"
#include "Button_dec_aliases.h"
#include "button_dec_isr.h"
#include "LCD_Char.h"
#include "QuadDec.h"
#include "Clock_1.h"
#include "A.h"
#include "A_aliases.h"
#include "B.h"
#include "B_aliases.h"
#include "Button_direction.h"
#include "Button_direction_aliases.h"
#include "button_direction_isr.h"
#include "Timer_Counter.h"
#include "Clock.h"
#include "timer_isr.h"
#include "PWM.h"
#include "Clock_2.h"
#include "LCD_Char_LCDPort.h"
#include "LCD_Char_LCDPort_aliases.h"
#include "QuadDec_Cnt8.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

